### ISSUE TITLE
疑似和B.A.S.E.冲突

### ISSUE THREAD

**Issue by su226** [CFPAOrg/I18nUpdateMod#18]
我希望将GTCE的语言条目material.uranium从铀238改为铀，同时增加单独的铀238材料，以此来兼容NuclearCraft，所以我尝试使用B.A.S.E.的外部资源功能，但是却被汉化更新模组的资源覆盖掉了。
所以我希望使汉化更新模组的优先级低于B.A.S.E.的优先级，方便制作整合包。
B.A.S.E.版本：3.11.0
更新模组版本：1.0.7

**Comment by Yesterday17** [comment]
这个是原版资源包的机制吧？你可以试试再挂一个资源包把i18n加载的资源包覆盖掉？

i18n的本质是下完资源包并且在options.txt里加了一行而已，用的是原版资源包的特性。

**Comment by SeraphJACK** [comment]
@Yesterday17 不不不，i18nupdatemod是在construction阶段覆盖resourcepack repository强行加入，没有动options.txt...

**Comment by Yesterday17** [comment]
我的建议是在这种情况下用contenttweaker重新搓一个item 然后把原来的给隐藏
这样对这个Item来说不存在语言冲突 甚至可以设置独立的语言条目 方便国际化

**Comment by TartaricAcid** [comment]
https://github.com/CFPAOrg/I18nUpdateMod/releases/tag/1.0.8
我发布了新版本，你试试
