### ISSUE TITLE
Linux 下无法下载资源包

### ISSUE THREAD

**Issue by scikirbypoke** [CFPAOrg/I18nUpdateMod#20]
启动时会这样
![2019-02-15_18-51](https://user-images.githubusercontent.com/11038263/52852524-cf364e00-3153-11e9-9e76-54bf244de26e.png)
一段时间后会这样
![2019-02-15_18-54](https://user-images.githubusercontent.com/11038263/52852564-f1c86700-3153-11e9-9ea4-5cfaf957e725.png)
切到Windows下能正常下载
版本是1.0.8

**Comment by SeraphJACK** [comment]
有日志文件吗

**Comment by scikirbypoke** [comment]
启动时似乎没有相关，进入世界时会提示
![2019-02-15_19-51](https://user-images.githubusercontent.com/11038263/52854984-255abf80-315b-11e9-8ab5-6defd15d8b62.png)
然后才有这样的日志
https://pastebin.com/sptajCZD

**Comment by SeraphJACK** [comment]
确定dns配置没问题吗

**Comment by scikirbypoke** [comment]
没事了，抓了半天包发现是多年前的java代理设置没有删掉
