### ISSUE TITLE
与Flex FOV这个模组存在不兼容问题

### ISSUE THREAD

**Issue by sjackser** [CFPAOrg/I18nUpdateMod#30]
![HD`63@X7P2F2 KQVI4%4D97](https://user-images.githubusercontent.com/24774842/68917034-7c9dc700-07a3-11ea-8141-66debf2b7ddd.png)
在渲染的时候会出现这样的问题.
值得一提的是, 根据我的测试, 任何一个可能涉及到GUI更改的模组(如ThaumicJEI, HammerCore, 甚至Xaero's Minimap??)可能都会导致该mod出现这个问题, 目前我已经向原作者反馈. 
不知道i18n这边能不能做出什么workaround呢…

**Comment by TartaricAcid** [comment]
问题是……我并没有更改任何 GUI 啊

**Comment by sjackser** [comment]
问题是确实我打上了i18n update mod以后，FlexFOV的渲染就开始不正常了。我这边可以反复测试出这一问题。
我能不能提供更加详细的信息一类的？

**Comment by TartaricAcid** [comment]
这个我回头查看下，如果问题还是无法解决，目前可以通过手动安装资源包，删除自动汉化更新模组来实现

**Comment by sjackser** [comment]
目前我确实是这么做的（）十分感谢

**Comment by SeraphJACK** [comment]
会不会是改 options 的操作和那个 mod 不兼容？

**Comment by sjackser** [comment]
> 会不会是改 options 的操作和那个 mod 不兼容？
改Options?

**Comment by SeraphJACK** [comment]
强制修改语言成中文的操作

**Comment by sjackser** [comment]
> 强制修改语言成中文的操作

这个具体我不是很明白了，因为我原本用的就是中文语言…

**Comment by SeraphJACK** [comment]
这是 i18nupdatemod 的原理之一..

**Comment by sjackser** [comment]
> 这是 i18nupdatemod 的原理之一..

具体运作原理究竟是怎么样的？就这样一条我很难找到它和ThaumicJEI，Xaero's Minimap之间的共同之处…已知HammerCore(Hammer Lib)这个mod里面有一个Smoothier Vanilla GUI功能会导致冲突问题，可能是更改了比GUI更深的东西…?

**Comment by SeraphJACK** [comment]
就是下载资源包放到资源包目录，然后在 Constrution 阶段覆写 options 切换语言和加载资源包

**Comment by sjackser** [comment]
我不觉得这个会造成问题…哦，以及我在设置里有关掉强制切换语言和强制更改资源包，问题也是一样的
