### ISSUE TITLE
当热键更改为分号时会崩溃

### ISSUE THREAD

**Issue by Simba98** [CFPAOrg/I18nUpdateMod#31]
以下是Crash Report

> Description: Updating screen events
> 
> java.lang.IndexOutOfBoundsException
>     at java.nio.Buffer.checkIndex(Unknown Source)
>     at java.nio.DirectByteBuffer.get(Unknown Source)
>     at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
>     at org.cfpa.i18nupdatemod.hotkey.HotKeyHandler.reloadLocalization(HotKeyHandler.java:243)
>     at org.cfpa.i18nupdatemod.hotkey.HotKeyHandler.onKeyPress(HotKeyHandler.java:72)
>     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_627_HotKeyHandler_onKeyPress_Pre.invoke(.dynamic)
>     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
>     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
>     at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:511)
>     at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
>     at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
>     at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
>     at net.minecraft.client.main.Main.main(SourceFile:123)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>     at java.lang.reflect.Method.invoke(Unknown Source)
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TartaricAcid** [comment]
这个问题在最新版模组中解决了，关闭此 issues
