### ISSUE TITLE
自动汉化更新模组未能成功拉取新版本资源包

### ISSUE THREAD

**Issue by RisingInIris2017** [CFPAOrg/I18nUpdateMod#32]
#### MOD版本 - Mod version:

i18nupdatemod-1.12.2-1.0.8

#### Forge版本 - Forge version:

forge-1.12.2-14.23.5.2847

#### 单人/多人游戏？ - Singleplayer or Multiplayer:

Both Singleplayer and Multiplayer

#### 完整的MOD列表 - Installed mods:

![](https://user-images.githubusercontent.com/28519848/72961436-02657080-3dec-11ea-93f1-e302c2ebdbe0.png)

## 问题描述 - Description of the problem
我向中文资源包repo发出的更新污秽之地PR在1月21日下午被merge.
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/6d0f093541e5320bc42c0b118ce623a9ba1b16ab
但是至今为止，我的整合包仍然未能收到中文资源包的更新。
客户端resourcepacks文件夹显示的文件修改日期是1月14日：
![TIM截图20200126165419](https://user-images.githubusercontent.com/28519848/73132915-8887ee00-405c-11ea-80b5-4d6e73849e46.png)
但每次启动客户端，都没有出现资源包更新的弹窗。

客户端 [latest.log](https://github.com/CFPAOrg/I18nUpdateMod/files/4113270/latest.log)

这个问题不知道是什么情况。
希望可以得到各位大佬们的帮助，感谢！

**Comment by SeraphJACK** [comment]
估计是没上传到七牛云吧 @TartaricAcid ，和 mod 本身应该没关系。

**Comment by Summpot** [comment]
可能是传失败了，话说mc对资源包的压缩算法有讲究么？ @SeraphJACK

**Comment by RisingInIris2017** [comment]
那也不能这么多个release每个都传失败了吧（小声
怎么给人一种酒石酸dalao忘记给服务器续费的错觉（

**Comment by Summpot** [comment]
不知道啊（

**Comment by Summpot** [comment]
@RisingInIris2017 已修复
