### ISSUE TITLE
在整合包Eternal中会与Farseek 发声冲突

### ISSUE THREAD

**Issue by jwthly** [CFPAOrg/I18nUpdateMod#33]
https://paste.ubuntu.com/p/9xR9T8FCbm/

**Comment by SeraphJACK** [comment]
https://github.com/Furgl/Stupid-Things/blob/8e8c6cf46595de7df4950f1fdda2b8e11cb7d8a6/src/main/java/furgl/stupidThings/common/fluid/ModFluids.java#L68

在这里的 NPE 为什么断定和 I18nUpdateMod 有关？

**Comment by jwthly** [comment]
抱歉，我说的有点不够仔细，是在加载汉化的材质包以后出现的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seraph_JACK"<notifications@github.com&gt;; 
发送时间: 2020年2月2日(星期天) 晚上11:29
收件人: "CFPAOrg/I18nUpdateMod"<I18nUpdateMod@noreply.github.com&gt;; 
抄送: "九尾天狐"<307274085@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CFPAOrg/I18nUpdateMod] 在整合包Eternal中会与Farseek 发声冲突 (#33)




https://github.com/Furgl/Stupid-Things/blob/8e8c6cf46595de7df4950f1fdda2b8e11cb7d8a6/src/main/java/furgl/stupidThings/common/fluid/ModFluids.java#L68
 
在这里的 NPE 为什么断定和 I18nUpdateMod 有关？

**Comment by SeraphJACK** [comment]
所以只要加了资源包就会出现问题，无论有没有使用 I18nUpdateMod 吗？

**Comment by jwthly** [comment]
是的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seraph_JACK"<notifications@github.com&gt;; 
发送时间: 2020年2月2日(星期天) 晚上11:38
收件人: "CFPAOrg/I18nUpdateMod"<I18nUpdateMod@noreply.github.com&gt;; 
抄送: "九尾天狐"<307274085@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CFPAOrg/I18nUpdateMod] 在整合包Eternal中会与Farseek 发声冲突 (#33)




所以只要加了资源包就会出现问题，无论有没有使用 I18nUpdateMod 吗？
 
&mdash;

**Comment by SeraphJACK** [comment]
根据错误报告看，应该是 stupid things 这个模组的问题。但是我尝试在客户端安装了最新版的 stupid things 和汉化资源包，并没有发生这个问题，能不能麻烦你尝试找出最少模组复现情况？

**Comment by jwthly** [comment]
问题貌似出在和farseek这个前置mod的流体注册冲突了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seraph_JACK"<notifications@github.com&gt;; 
发送时间: 2020年2月2日(星期天) 晚上11:45
收件人: "CFPAOrg/I18nUpdateMod"<I18nUpdateMod@noreply.github.com&gt;; 
抄送: "九尾天狐"<307274085@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CFPAOrg/I18nUpdateMod] 在整合包Eternal中会与Farseek 发声冲突 (#33)




根据错误报告看，应该是 stupid things 这个模组的问题。但是我尝试在客户端安装了最新版的 stupid things 和汉化资源包，并没有发生这个问题，能不能麻烦你尝试找出最少模组复现情况？
 
&mdash;

**Comment by SeraphJACK** [comment]
但是我想不通这和本地化有什么联系，而且我把 farseek 和 stupidthings 同时安装也没有出现问题。

![Screenshot_20200202_235011](https://user-images.githubusercontent.com/25274081/73610850-c2399580-4616-11ea-99df-4bea24935e1e.png)

![Screenshot_20200202_235029](https://user-images.githubusercontent.com/25274081/73610853-cc5b9400-4616-11ea-96b3-2a58b0a74db5.png)

**Comment by SeraphJACK** [comment]
请尝试移除整合包里其他不依赖 farseek 的模组，然后从依赖 farseek 的模组中二分法找出出错的模组？

**Comment by jwthly** [comment]
是stream



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seraph_JACK"<notifications@github.com&gt;; 
发送时间: 2020年2月2日(星期天) 晚上11:53
收件人: "CFPAOrg/I18nUpdateMod"<I18nUpdateMod@noreply.github.com&gt;; 
抄送: "九尾天狐"<307274085@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CFPAOrg/I18nUpdateMod] 在整合包Eternal中会与Farseek 发声冲突 (#33)




请尝试移除整合包里其他不依赖 farseek 的模组，然后从依赖 farseek 的模组中二分法找出出错的模组？
 
&mdash;

**Comment by SeraphJACK** [comment]
安装 streams 以后仍然无法复现，这个模组包中除了 stupid things 模组，是否还有其他模组有酸这个流体？

**Comment by jwthly** [comment]
mek和nuclearcraft




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seraph_JACK"<notifications@github.com&gt;; 
发送时间: 2020年2月3日(星期一) 凌晨0:02
收件人: "CFPAOrg/I18nUpdateMod"<I18nUpdateMod@noreply.github.com&gt;; 
抄送: "九尾天狐"<307274085@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CFPAOrg/I18nUpdateMod] 在整合包Eternal中会与Farseek 发声冲突 (#33)




安装 streams 以后仍然无法复现，这个模组包中除了 stupid things 模组，是否还有其他模组有酸这个流体？
 
&mdash;

**Comment by SeraphJACK** [comment]
能否把整合包的config文件夹发一下？

**Comment by jwthly** [comment]
https://www.lanzous.com/i90ahcd




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seraph_JACK"<notifications@github.com&gt;; 
发送时间: 2020年2月3日(星期一) 凌晨0:21
收件人: "CFPAOrg/I18nUpdateMod"<I18nUpdateMod@noreply.github.com&gt;; 
抄送: "九尾天狐"<307274085@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CFPAOrg/I18nUpdateMod] 在整合包Eternal中会与Farseek 发声冲突 (#33)




能否把整合包的config文件夹发一下？
 
&mdash;

**Comment by SeraphJACK** [comment]
在未汉化的时候，酸液对应的条目是 Acid ，在源配置文件里有：

```
B:Acid=false
```

增加汉化资源包之后，自动生成了新的对应配置，且默认值为 `true` :

```
B:酸液=true
```

在配置文件将此项改为 false 应该可以解决问题。另，这应该属于 `stupidthings` 模组的设计缺陷，如果有必要请向 `stupidthings` 模组的仓库[发 issue ticket](https://github.com/Furgl/Stupid-Things/issues)。无论如何，这不是汉化资源包的问题。

**Comment by jwthly** [comment]
问题解决！辛苦！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seraph_JACK"<notifications@github.com&gt;; 
发送时间: 2020年2月3日(星期一) 凌晨0:28
收件人: "CFPAOrg/I18nUpdateMod"<I18nUpdateMod@noreply.github.com&gt;; 
抄送: "九尾天狐"<307274085@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CFPAOrg/I18nUpdateMod] 在整合包Eternal中会与Farseek 发声冲突 (#33)




在未汉化的时候，酸液对应的条目是 Acid ，在源配置文件里有：
 B:Acid=false  
增加汉化资源包之后，自动生成了新的对应配置，且默认值为 true :
 B:酸液=true  
在配置文件将此项改为 false 应该可以解决问题。另，这应该属于 stupidthings 模组的设计缺陷，如果有必要请向 stupidthings 模组的仓库发 issue ticket。无论如何，这不是汉化资源包的问题。
 
&mdash;
