### ISSUE TITLE
格雷空岛（Greg Block）中的翻译把液体单位“毫升”翻译成了“升”

### ISSUE THREAD

**Issue by Lievent5703** [CFPAOrg/I18nUpdateMod#35]
格雷空岛（Greg Block）中的翻译把液体单位“毫升”翻译成了“升”

不管是管道流量还是桶装液体单位都显示为“升”

已使用Greg Block整合包汉化2.2.1  和  i18n汉化模组

**Comment by Yesterday17** [comment]
请至汉化资源包仓库或整合包汉化仓库反馈。
