### ISSUE TITLE
BUG 反馈

### ISSUE THREAD

**Issue by liuhaoxin10** [CFPAOrg/I18nUpdateMod#36]
### 描述
the game crashed when l launch it,please help to check out what had happened.l will appreciate if you can help me as soon as possible

### 日志/崩溃报告

https://paste.ubuntu.com/p/bRzkFjJSsY/

**Comment by SeraphJACK** [comment]
嗯.. 你可以直接说中文的。

简述一下为什么你认为这是 I18nUpdateMod 的问题？

**Comment by liuhaoxin10** [comment]
好的，抱歉，我认为是I18nUpdateMod的问题，因为我将I18nUpdateMod移除之后，就没有问题了。还有我用的是Mac OS系统

**Comment by liuhaoxin10** [comment]
我装载的是Eternal_minecraft 这个整合包，除去I18nUpdateMod之外一共有304个模组

**Comment by 3TUSK** [comment]
https://github.com/Furgl/Stupid-Things/blob/b7b3d1dd228f894dfac5a8ce807e4b99d36520b9/src/main/java/furgl/stupidThings/common/fluid/ModFluids.java#L49-L50

Stupid-Things 的问题。配置文件不是这么用的。

**Comment by liuhaoxin10** [comment]
那请问具体该怎么样操作，才能正确开启

**Comment by 3TUSK** [comment]
是一个叫 Stupid Things 的 Mod 的问题。我不确定删除这个 Mod 会不会对你的整合造成影响。删 Mod 前请备份。

**Comment by liuhaoxin10** [comment]
好的，感谢你的帮助，我会试试看的

**Comment by SeraphJACK** [comment]
嗯.. 我说怎么有点眼熟来着。 #33
