### ISSUE TITLE
BUG 反馈

### ISSUE THREAD

**Issue by liuhaoxin10** [CFPAOrg/I18nUpdateMod#37]
### 描述
抱歉，游戏有出路问题，在去掉stupid things之后能够启动了，但是进入世界之后，打开物品栏瞬间游戏崩溃

### 日志/崩溃报告

https://paste.ubuntu.com/p/C9pnq7DcCs/

**Comment by SeraphJACK** [comment]
#33

**Comment by SeraphJACK** [comment]
这个 hotkey 的问题早就修了，你需要更新 [i18nupdatemod](https://www.curseforge.com/minecraft/mc-mods/i18nupdatemod/files) 版本。

**Comment by SeraphJACK** [comment]
之前你问的 Stupidthings 问题，在 #33 已经有解决方案了，不需要删掉。
