### ISSUE TITLE
与Custom Main Menu同时运行时按下Ctrl+R（主界面刷新）导致崩溃

### ISSUE THREAD

**Issue by ghost** [CFPAOrg/I18nUpdateMod#48]
https://paste.ubuntu.com/p/VdbDczpFhs/

**Comment by SeraphJACK** [comment]
现在所有 I18nUpdateMod 的 issue 因为新版本没发布都没法及时修复和推送... 抄送 @TartaricAcid

**Comment by TartaricAcid** [comment]
这个问题在最新版中解决了，关闭此 issues
