### ISSUE TITLE
装有工业模组后使用该模组，语言文件全变英文，需要手动切换

### ISSUE THREAD

**Issue by TartaricAcid** [CFPAOrg/I18nUpdateMod#5]
玩家反馈的信息

**Comment by SeraphJACK** [comment]
是指gameSetting里的语言变成英语了还是资源包没有加载，或者是只有工业这个模组的语言文件没有加载？

**Comment by TartaricAcid** [comment]
只有工业这个模组的语言文件没有加载，需要玩家手动重新切换英文，而后切换中文，看起来工业模组读取语言比我们的模组还早

**Comment by 3TUSK** [comment]
https://github.com/CFPAOrg/I18nUpdateMod/blob/00bd69fc39ddc9094a1bbcf268bf240a859abe88/src/main/java/org/cfpa/i18nupdatemod/I18nUtils.java#L108-L111

Add
```java
gameSettings.language = "zh_cn";
```
in `if` clause.

**Comment by SeraphJACK** [comment]
Fixed
不过还没验证
