### ISSUE TITLE
资源包下载失败

### ISSUE THREAD

**Issue by JiuMuln** [CFPAOrg/I18nUpdateMod#51]
i18n版本是1.12.2 mod版本1.1.0
forge版本1.12.2 内部版本：14.23.5.2855
情况：在进入游戏的fml预加载阶段，i18n总是下载资源包失败，且没有在配置文件夹里面生成i18n的配置文件

**Comment by JiuMuln** [comment]
需不需要上传完整的运行日志啊

**Comment by TartaricAcid** [comment]
需要，有助于我们分析问题

**Comment by JiuMuln** [comment]
已更新日志，再附上debug日志，资源包已经下载了，不过配置文件夹依旧没有i18n的配置文件
[debug.log](https://github.com/CFPAOrg/I18nUpdateMod/files/5741654/debug.log)
