### ISSUE TITLE
在1.15.2的 沉浸工程(ImmersiveEngineering) 中 打开 工程师手册 导致客户端崩溃

### ISSUE THREAD

**Issue by MZhihe** [CFPAOrg/I18nUpdateMod#53]
https://paste.ubuntu.com/p/YBNycmtBTX/

**Comment by MZhihe** [comment]
So.... How can this problem be solved?

**Comment by SeraphJACK** [comment]
首先，你没有按照 issue template 填写描述。不仅没有按照模板填写信息，上传的 crash-report 里提到了需要 log 也没有上传，根本没有办法分析问题具体出在哪里。

其次，这个问题已经在此之前已经被提过了：[Minecraft-Mod-Language-Package#921](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/921)

最后，基本可以确定这个问题是汉化资源包本身导致的，而不是汉化更新模组导致的，你在这发 issue 也没用（上面那个 issue 也被我 transfer 到资源包那边去了）。

另外，高版本的汉化更新模组和这个仓库的更新模组完全不是一个东西，维护者也完全不同。所以即使你确定了是汉化更新模组的问题，这个仓库的维护者也没有办法提供帮助。

综上，我只能关闭这个 issue 。

**Comment by MZhihe** [comment]
多谢
